import type { BooleanKeys } from "../../domain/models/plant-data.model";

export const occurenceKeys: BooleanKeys[] = [
    'anthill',
    'broken_branch',
    'burnt_branch',
    'drill',
    'empty_collection_box_near',
    'fertilization_or_manuring',
    'in_experiment',
    'is_dead',
    'mites',
    'stick',
    'struck_by_lightning',
    'thrips',
    'vine_growing',
    'weeds_in_the_basin',
    'is_new',
    'non_existent',
    'frost',
    'flowers',
    'buds',
    'dehydrated',
];

export const occurencesLabels: Record<string, string> = {
    stick: 'COMMON.OCCURRENCES_LABELS.STICK',
    broken_branch: 'COMMON.OCCURRENCES_LABELS.BROKEN_BRANCH',
    vine_growing: 'COMMON.OCCURRENCES_LABELS.VINE_GROWING',
    burnt_branch: 'COMMON.OCCURRENCES_LABELS.BURNT_BRANCH',
    struck_by_lightning: 'COMMON.OCCURRENCES_LABELS.STRUCK_BY_LIGHTNING',
    drill: 'COMMON.OCCURRENCES_LABELS.DRILL',
    anthill: 'COMMON.OCCURRENCES_LABELS.ANTHILL',
    in_experiment: 'COMMON.OCCURRENCES_LABELS.IN_EXPERIMENT',
    weeds_in_the_basin: 'COMMON.OCCURRENCES_LABELS.WEEDS_IN_THE_BASIN',
    is_dead: 'COMMON.OCCURRENCES_LABELS.IS_DEAD',
    mites: 'COMMON.OCCURRENCES_LABELS.MITES',
    thrips: 'COMMON.OCCURRENCES_LABELS.THRIPS',
    empty_collection_box_near: 'COMMON.OCCURRENCES_LABELS.EMPTY_COLLECTION_BOX_NEAR',
    fertilization_or_manuring: 'COMMON.OCCURRENCES_LABELS.FERTILIZATION_OR_MANURING',
    is_new: 'COMMON.OCCURRENCES_LABELS.IS_NEW',
    non_existent: 'COMMON.OCCURRENCES_LABELS.NON_EXISTENT',
    frost: 'COMMON.OCCURRENCES_LABELS.FROST',
    flowers: 'COMMON.OCCURRENCES_LABELS.FLOWERS',
    buds: 'COMMON.OCCURRENCES_LABELS.BUDS',
    dehydrated: 'COMMON.OCCURRENCES_LABELS.DEHYDRATED',
};